name: release
on:
  push:
    branches:
    - main
jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.tag.outputs.changelog }}
      tag: ${{ steps.tag.outputs.new_tag }}
      version: ${{ steps.tag.outputs.new_version }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Bump version and tag
      uses: mathieudutour/github-tag-action@v6.0
      id: tag
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.17'
    - name: Build
      run: |
        BINARY_NAME=scra-${{matrix.goos}}-${{matrix.goarch}}
        GOOS=${{matrix.goos}} GOARCH=${{matrix.goarch}} go build -o $BINARY_NAME -v
    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: scra-artifact
        path: scra-*-*

  containers:
    runs-on: ubuntu-latest
    needs: tag
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push containers
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/${{ github.repository }}:${{ needs.tag.outputs.tag }}
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}

  release:
    needs:
    - tag
    - containers
    - binaries
    runs-on: ubuntu-latest
    steps:
    - name: Restore artifact
      uses: actions/download-artifact@v3
      with:
        name: scra-artifact
    - name: Create checksums
      run: |
        sha256sum scra-*-* | tee scra.sha256
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.tag.outputs.tag }}
        name: Release ${{ needs.tag.outputs.version }}
        body: |
          Changes in this release:

          ${{ needs.tag.outputs.changelog }}

          Docker image: ghcr.io/${{ github.repository }}:${{ needs.tag.outputs.tag }}
        files: scra-*-*,scra.sha256
