name: tests
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.17'
    - name: Verify dependencies
      run: go mod verify
    - name: Run go vet
      run: go vet ./...
    - name: Staticcheck
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1"
    - name: Run go build
      run: go build -v
