name: tests
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: '1.17'
    - name: Set up buildx
      uses: docker/setup-buildx-action@v1
    - name: Verify dependencies
      run: go mod verify
    - name: Run go vet
      run: go vet ./...
    - name: Staticcheck
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1"
    - name: Run go build
      run: go build -v
    - name: Build containers
      uses: docker/build-push-action@v2
      with:
        push: false
        platforms: linux/amd64,linux/arm64
